# Generated by Django 4.1.6 on 2023-02-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_song_songs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
